// js/allCountries.js

const allCountries = [
  { name: "Afghanistan", emoji: "🇦🇫" },
  { name: "Afrique du Sud", emoji: "🇿🇦" },
  { name: "Albanie", emoji: "🇦🇱" },
  { name: "Algérie", emoji: "🇩🇿" },
  { name: "Allemagne", emoji: "🇩🇪" },
  { name: "Andorre", emoji: "🇦🇩" },
  { name: "Angola", emoji: "🇦🇴" },
  { name: "Arabie Saoudite", emoji: "🇸🇦" },
  { name: "Argentine", emoji: "🇦🇷" },
  { name: "Arménie", emoji: "🇦🇲" },
  { name: "Australie", emoji: "🇦🇺" },
  { name: "Autriche", emoji: "🇦🇹" },
  { name: "Azerbaïdjan", emoji: "🇦🇿" },
  { name: "Bahamas", emoji: "🇧🇸" },
  { name: "Bahreïn", emoji: "🇧🇭" },
  { name: "Bangladesh", emoji: "🇧🇩" },
  { name: "Barbade", emoji: "🇧🇧" },
  { name: "Belgique", emoji: "🇧🇪" },
  { name: "Bénin", emoji: "🇧🇯" },
  { name: "Bhoutan", emoji: "🇧🇹" },
  { name: "Biélorussie", emoji: "🇧🇾" },
  { name: "Birmanie", emoji: "🇲🇲" },
  { name: "Bolivie", emoji: "🇧🇴" },
  { name: "Bosnie-Herzégovine", emoji: "🇧🇦" },
  { name: "Botswana", emoji: "🇧🇼" },
  { name: "Brésil", emoji: "🇧🇷" },
  { name: "Brunei", emoji: "🇧🇳" },
  { name: "Bulgarie", emoji: "🇧🇬" },
  { name: "Burkina Faso", emoji: "🇧🇫" },
  { name: "Burundi", emoji: "🇧🇮" },
  { name: "Cambodge", emoji: "🇰🇭" },
  { name: "Cameroun", emoji: "🇨🇲" },
  { name: "Canada", emoji: "🇨🇦" },
  { name: "Cap-Vert", emoji: "🇨🇻" },
  { name: "Chili", emoji: "🇨🇱" },
  { name: "Chine", emoji: "🇨🇳" },
  { name: "Chypre", emoji: "🇨🇾" },
  { name: "Colombie", emoji: "🇨🇴" },
  { name: "Comores", emoji: "🇰🇲" },
  { name: "Congo (Brazzaville)", emoji: "🇨🇬" },
  { name: "Congo (Kinshasa)", emoji: "🇨🇩" },
  { name: "Corée du Nord", emoji: "🇰🇵" },
  { name: "Corée du Sud", emoji: "🇰🇷" },
  { name: "Costa Rica", emoji: "🇨🇷" },
  { name: "Côte d'Ivoire", emoji: "🇨🇮" },
  { name: "Croatie", emoji: "🇭🇷" },
  { name: "Cuba", emoji: "🇨🇺" },
  { name: "Danemark", emoji: "🇩🇰" },
  { name: "Djibouti", emoji: "🇩🇯" },
  { name: "Dominique", emoji: "🇩🇲" },
  { name: "Égypte", emoji: "🇪🇬" },
  { name: "Émirats Arabes Unis", emoji: "🇦🇪" },
  { name: "Équateur", emoji: "🇪🇨" },
  { name: "Érythrée", emoji: "🇪🇷" },
  { name: "Espagne", emoji: "🇪🇸" },
  { name: "Estonie", emoji: "🇪🇪" },
  { name: "Eswatini", emoji: "🇸🇿" },
  { name: "États-Unis", emoji: "🇺🇸" },
  { name: "Éthiopie", emoji: "🇪🇹" },
  { name: "Fidji", emoji: "🇫🇯" },
  { name: "Finlande", emoji: "🇫🇮" },
  { name: "France", emoji: "🇫🇷" },
  { name: "Gabon", emoji: "🇬🇦" },
  { name: "Gambie", emoji: "🇬🇲" },
  { name: "Géorgie", emoji: "🇬🇪" },
  { name: "Ghana", emoji: "🇬🇭" },
  { name: "Grèce", emoji: "🇬🇷" },
  { name: "Grenade", emoji: "🇬🇩" },
  { name: "Guatemala", emoji: "🇬🇹" },
  { name: "Guinée", emoji: "🇬🇳" },
  { name: "Guinée équatoriale", emoji: "🇬🇶" },
  { name: "Guinée-Bissau", emoji: "🇬🇼" },
  { name: "Guyana", emoji: "🇬🇾" },
  { name: "Haïti", emoji: "🇭🇹" },
  { name: "Honduras", emoji: "🇭🇳" },
  { name: "Hongrie", emoji: "🇭🇺" },
  { name: "Inde", emoji: "🇮🇳" },
  { name: "Indonésie", emoji: "🇮🇩" },
  { name: "Irak", emoji: "🇮🇶" },
  { name: "Iran", emoji: "🇮🇷" },
  { name: "Irlande", emoji: "🇮🇪" },
  { name: "Islande", emoji: "🇮🇸" },
  { name: "Israël", emoji: "🇮🇱" },
  { name: "Italie", emoji: "🇮🇹" },
  { name: "Jamaïque", emoji: "🇯🇲" },
  { name: "Japon", emoji: "🇯🇵" },
  { name: "Jordanie", emoji: "🇯🇴" },
  { name: "Kazakhstan", emoji: "🇰🇿" },
  { name: "Kenya", emoji: "🇰🇪" },
  { name: "Kirghizistan", emoji: "🇰🇬" },
  { name: "Kiribati", emoji: "🇰🇮" },
  { name: "Koweït", emoji: "🇰🇼" },
  { name: "Laos", emoji: "🇱🇦" },
  { name: "Lesotho", emoji: "🇱🇸" },
  { name: "Lettonie", emoji: "🇱🇻" },
  { name: "Liban", emoji: "🇱🇧" },
  { name: "Libéria", emoji: "🇱🇷" },
  { name: "Libye", emoji: "🇱🇾" },
  { name: "Liechtenstein", emoji: "🇱🇮" },
  { name: "Lituanie", emoji: "🇱🇹" },
  { name: "Luxembourg", emoji: "🇱🇺" },
  { name: "Macédoine", emoji: "🇲🇰" },
  { name: "Madagascar", emoji: "🇲🇬" },
  { name: "Malaisie", emoji: "🇲🇾" },
  { name: "Malawi", emoji: "🇲🇼" },
  { name: "Maldives", emoji: "🇲🇻" },
  { name: "Mali", emoji: "🇲🇱" },
  { name: "Malte", emoji: "🇲🇹" },
  { name: "Maroc", emoji: "🇲🇦" },
  { name: "Maurice", emoji: "🇲🇺" },
  { name: "Mauritanie", emoji: "🇲🇷" },
  { name: "Mexique", emoji: "🇲🇽" },
  { name: "Moldavie", emoji: "🇲🇩" },
  { name: "Monaco", emoji: "🇲🇨" },
  { name: "Mongolie", emoji: "🇲🇳" },
  { name: "Monténégro", emoji: "🇲🇪" },
  { name: "Mozambique", emoji: "🇲🇿" },
  { name: "Namibie", emoji: "🇳🇦" },
  { name: "Népal", emoji: "🇳🇵" },
  { name: "Nicaragua", emoji: "🇳🇮" },
  { name: "Niger", emoji: "🇳🇪" },
  { name: "Nigeria", emoji: "🇳🇬" },
  { name: "Norvège", emoji: "🇳🇴" },
  { name: "Nouvelle-Zélande", emoji: "🇳🇿" },
  { name: "Oman", emoji: "🇴🇲" },
  { name: "Ouganda", emoji: "🇺🇬" },
  { name: "Ouzbékistan", emoji: "🇺🇿" },
  { name: "Pakistan", emoji: "🇵🇰" },
  { name: "Palestine", emoji: "🇵🇸" },
  { name: "Panama", emoji: "🇵🇦" },
  { name: "Papouasie-Nouvelle-Guinée", emoji: "🇵🇬" },
  { name: "Paraguay", emoji: "🇵🇾" },
  { name: "Pays-Bas", emoji: "🇳🇱" },
  { name: "Pérou", emoji: "🇵🇪" },
  { name: "Philippines", emoji: "🇵🇭" },
  { name: "Pologne", emoji: "🇵🇱" },
  { name: "Portugal", emoji: "🇵🇹" },
  { name: "Qatar", emoji: "🇶🇦" },
  { name: "République Centrafricaine", emoji: "🇨🇫" },
  { name: "République Tchèque", emoji: "🇨🇿" },
  { name: "Roumanie", emoji: "🇷🇴" },
  { name: "Royaume-Uni", emoji: "🇬🇧" },
  { name: "Russie", emoji: "🇷🇺" },
  { name: "Rwanda", emoji: "🇷🇼" },
  { name: "Saint-Marin", emoji: "🇸🇲" },
  { name: "Saint-Siège", emoji: "🇻🇦" },
  { name: "Salvador", emoji: "🇸🇻" },
  { name: "Samoa", emoji: "🇼🇸" },
  { name: "Sénégal", emoji: "🇸🇳" },
  { name: "Serbie", emoji: "🇷🇸" },
  { name: "Seychelles", emoji: "🇸🇨" },
  { name: "Sierra Leone", emoji: "🇸🇱" },
  { name: "Singapour", emoji: "🇸🇬" },
  { name: "Slovaquie", emoji: "🇸🇰" },
  { name: "Slovénie", emoji: "🇸🇮" },
  { name: "Somalie", emoji: "🇸🇴" },
  { name: "Soudan", emoji: "🇸🇩" },
  { name: "Soudan du Sud", emoji: "🇸🇸" },
  { name: "Sri Lanka", emoji: "🇱🇰" },
  { name: "Suède", emoji: "🇸🇪" },
  { name: "Suisse", emoji: "🇨🇭" },
  { name: "Suriname", emoji: "🇸🇷" },
  { name: "Syrie", emoji: "🇸🇾" },
  { name: "Tadjikistan", emoji: "🇹🇯" },
  { name: "Tanzanie", emoji: "🇹🇿" },
  { name: "Tchad", emoji: "🇹🇩" },
  { name: "Thaïlande", emoji: "🇹🇭" },
  { name: "Timor oriental", emoji: "🇹🇱" },
  { name: "Togo", emoji: "🇹🇬" },
  { name: "Tonga", emoji: "🇹🇴" },
  { name: "Trinité-et-Tobago", emoji: "🇹🇹" },
  { name: "Tunisie", emoji: "🇹🇳" },
  { name: "Turkménistan", emoji: "🇹🇲" },
  { name: "Turquie", emoji: "🇹🇷" },
  { name: "Ukraine", emoji: "🇺🇦" },
  { name: "Uruguay", emoji: "🇺🇾" },
  { name: "Vanuatu", emoji: "🇻🇺" },
  { name: "Venezuela", emoji: "🇻🇪" },
  { name: "Vietnam", emoji: "🇻🇳" },
  { name: "Yémen", emoji: "🇾🇪" },
  { name: "Zambie", emoji: "🇿🇲" },
  { name: "Zimbabwe", emoji: "🇿🇼" }
];
